auctionsite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from . import views
from django.contrib.auth import views as django_auth_views


urlpatterns = [
    url(r'^admin/', include('admin_honeypot.urls', namespace='admin_honeypot')),
    url(r'^giaadmin/', admin.site.urls),
    url(r'^search/', include('haystack.urls')),
    url(r'^password_change/$', django_auth_views.PasswordChangeView.as_view(), name='password_change'),
    url(r'^password_change/done/$', django_auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^', include('items.urls', namespace="items")),
]

# Adding Static File Urls (for Dev environment only)
urlpatterns += staticfiles_urlpatterns()

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

items/urls.py
from django.conf.urls import include, url
from django.contrib.sitemaps.views import sitemap

from .sitemaps import ItemSitemap
from . import views

sitemaps = {
    'items': ItemSitemap()
}

urlpatterns = [

    # Sitemap
    url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),

    # Messages Actions
    url(r'^action/request-item/(?P<pk>\d+)/(?P<slug>[\w-]+)/$', views.RequestItemView.as_view(), name='request'),
    url(r'^action/offer-item/(?P<pk>\d+)/(?P<slug>[\w-]+)/$', views.OfferItemView.as_view(), name='offer'),
    url(r'^action/ask-question/(?P<pk>\d+)/(?P<slug>[\w-]+)/$', views.AskQuestionView.as_view(), name='ask'),
    url(r'^action/reply/(?P<pk>\d+)/(?P<slug>[\w-]+)/$', views.ReplyView.as_view(), name='reply'),
    url(r'^action/report-item/(?P<pk>\d+)/(?P<slug>[\w-]+)/$', views.ReportItemView.as_view(), name='report'),

    # Item CRUD Actions
    url(r'^action/create-item/$', views.ItemCreateView.as_view(), name='create'),
    url(r'^action/update-item/(?P<pk>\d+)/(?P<slug>[\w-]+)/$', views.ItemUpdateView.as_view(), name='update'),
    url(r'^action/delete-item/(?P<pk>\d+)/(?P<slug>[\w-]+)/$', views.ItemDeleteView.as_view(), name='delete'),

    # Item Completion Process
    url(r'^action/choose-user/(?P<pk>\d+)/(?P<username>[\w-]+)/$', views.ChooseUserView.as_view(), name='choose_user'),
    url(r'^action/make-available/(?P<pk>\d+)/$', views.MakeAvailableView.as_view(), name='make_available'),

    # Categories Views
    url(r'^item/category/(?P<pk>\d+)/(?P<slug>[\w-]+)/wanted-items/$', views.CategoryItemsWantedView.as_view(), name='category_items_wanted'),
    url(r'^item/category/(?P<pk>\d+)/(?P<slug>[\w-]+)/$', views.CategoryItemsView.as_view(), name='category_items'),

    # Profile View
    url(r'^user/(?P<username>\w+)/wanted/$', views.ProfileWantedView.as_view(), name='profile_wanted'),
    url(r'^user/(?P<username>\w+)/$', views.ProfileView.as_view(), name='profile'),

    # Tos
    url(r'^tos/$', views.TosTemplateView.as_view(), name='tos'),

    # Generic Views
    url(r'^dashboard/$', views.dashboard, name='dashboard'),
    url(r'^messages/$', views.profile_messages, name='profile_messages'),
    url(r'^item/(?P<pk>\d+)/(?P<slug>[\w-]+)/$', views.ItemDetailView.as_view(), name='detail'),
    url(r'^wanted-items/$', views.ItemWantedListView.as_view(), name='home_wanted'),
    url(r'^$', views.ItemListView.as_view(), name='home'),
]

items/models.py
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from django.utils import timezone
from django.template.defaultfilters import slugify
from django.db.models.signals import post_save
from django.dispatch import receiver
from cloudinary.models import CloudinaryField

from django.db import models



class Category(models.Model):
    title = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255, unique=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name_plural = "categories"
        ordering = ['title',]


class Item(models.Model):
    LOCATION_CHOICES = (
        ('AUH', 'Abu Dhabi'),
        ('AJM', 'Ajman'),
        ('SHJ', 'Sharjah'),
        ('DXB', 'Dubai'),
        ('FUJ', 'Fujairah'),
        ('RAK', 'Ras Al Khaimah'),
        ('UAQ', 'Umm Al Quwain'),
    )
    TYPE_CHOICES = (
        ('free', 'Free (I want to give something away)'),
        ('wanted', 'Wanted (I want to get something)'),
    )
    STATUS_CHOICES = (
        ('available', 'Available'),
        ('completed', 'Completed'),
        ('awaiting', 'Awaiting Pickup'),
        ('onhold', 'On Hold'),
        ('removed', 'Removed'),
    )
    name = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255)
    category = models.ForeignKey(Category, blank=True, null=True)
    other_category = models.CharField(max_length=128, blank=True, default="")
    details = models.TextField(blank=True, default="")
    posted_on = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User, related_name='item_user')
    completed_with = models.ForeignKey(User, blank=True, null=True, related_name='item_completed_with')
    location_detail = models.CharField(max_length=255, blank=True, null=True)

    # Cloudinary
    image1 = CloudinaryField('image', blank=True, null=True, default='')
    image2 = CloudinaryField('image', blank=True, null=True, default='')
    image3 = CloudinaryField('image', blank=True, null=True, default='')

    location = models.CharField(
        max_length=3,
        choices=LOCATION_CHOICES,
        default='DXB',
    )
    post_type = models.CharField(
        max_length=6,
        choices=TYPE_CHOICES,
        default='free',
    )
    status = models.CharField(
        max_length=10,
        choices=STATUS_CHOICES,
        default='available',
    )

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['-posted_on',]

    def get_absolute_url(self):
        return reverse("items:detail", kwargs={"pk":self.pk, "slug":self.slug})

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Item, self).save(*args, **kwargs)


class Activity(models.Model):
    TYPE_CHOICES = (
        ('available', 'Available'),
        ('offered', 'Offered'),
        ('requested', 'Requested'),
        ('awaiting', 'Awaiting Pickup'),
        ('completed', 'Completed'),
    )
    item = models.ForeignKey(Item, blank=True, null=True)
    user = models.ForeignKey(User, blank=True, null=True)
    date = models.DateTimeField(auto_now_add=True)
    change_type = models.CharField(
        max_length=9,
        choices=TYPE_CHOICES,
        blank=True,
        default='',
    )

    def __str__(self):
        return self.item.name

    class Meta:
        verbose_name_plural = "activities"


class UserMessage(models.Model):
    TAG_CHOICES = (
        ('request', 'Request'),
        ('offer', 'Offer'),
        ('question', 'Question'),
        ('report', 'Report'),
        ('reply', 'Reply'),
    )
    from_user = models.ForeignKey(User, related_name="usermessages")
    to_user = models.ForeignKey(User)
    item = models.ForeignKey(Item)
    date = models.DateTimeField(auto_now_add=True)
    pickup_time = models.CharField(max_length=255, blank=True, null=True)
    message = models.TextField()
    related_to = models.ForeignKey('self', blank=True, null=True)
    tag = models.CharField(
        max_length=9,
        choices=TAG_CHOICES,
        blank=True,
        default='request',
    )

    def __str__(self):
        return self.message

    class Meta:
        ordering = ['-date',]


class Profile(models.Model):
    LOCATION_CHOICES = (
        ('AUH', 'Abu Dhabi'),
        ('AJM', 'Ajman'),
        ('SHJ', 'Sharjah'),
        ('DXB', 'Dubai'),
        ('FUJ', 'Fujairah'),
        ('RAK', 'Ras Al Khaimah'),
        ('UAQ', 'Umm Al Quwain'),
    )
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    last_message_check = models.DateTimeField(blank=True, null=True)
    location = models.CharField(
        max_length=3,
        choices=LOCATION_CHOICES,
        default='DXB',
    )

    def __str__(self):
        return self.user.username


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)

@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    if not instance.is_superuser:
        instance.profile.save()

items/forms.py
from django.conf import settings
from django.contrib.auth.models import User
from django.template.defaultfilters import filesizeformat
from django.utils.translation import ugettext_lazy as _
from django import forms

from cloudinary.forms import CloudinaryFileField

from . import models



class ItemCreateForm(forms.ModelForm):
    image1 = CloudinaryFileField(
                required=False,
                options = {'crop': 'limit', 'width': 546, 'height': 1000,})
    image2 = CloudinaryFileField(
                required=False,
                options = {'crop': 'limit', 'width': 546, 'height': 1000,})
    image3 = CloudinaryFileField(
                required=False,
                options = {'crop': 'limit', 'width': 546, 'height': 1000,})
    class Meta:
        model = models.Item
        fields = ("post_type", "image1", "image2", "image3", "name", "details", "category", "other_category", "location", "location_detail")
        labels = {
            'details': _('Details (optional):'),
            'category': _('Category (optional):'),
            'other_category': _('Name the Other Category (optional):'),
            'location_detail': _('Location Detail (optional):'),
        }


class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name')


class SignupForm(forms.Form):
    accept_tos = forms.BooleanField(required=True, label='Accept terms of use')

    def signup(self, request, user):
        user.accept_tos = self.cleaned_data['accept_tos']
        user.save()


class ChooseUserForm(forms.ModelForm):
    STATUS_CHOICES = (
        ('awaiting', 'Awaiting Pickup'),
        ('completed', 'Completed'),
    )
    status = forms.ChoiceField(
        choices=STATUS_CHOICES,
    )
    class Meta:
        model = models.Item
        fields = ('status',)


class RequestForm(forms.ModelForm):
    class Meta:
        model = models.UserMessage
        fields = ['pickup_time', 'message']
        labels = {
            'pickup_time': 'Enter a date/day/time you can pickup the item:',
            'message': 'I\'d really like the item because:',
        }


class OfferForm(forms.ModelForm):
    class Meta:
        model = models.UserMessage
        fields = ['message']
        labels = {
            'message': 'Description of item offered',
        }


class ReplyForm(forms.ModelForm):
    class Meta:
        model = models.UserMessage
        fields = ['message']
        labels = {
            'message': 'Your Reply',
        }


class AskQuestionForm(forms.ModelForm):
    class Meta:
        model = models.UserMessage
        fields = ['message']
        labels = {
            'message': 'Your Question',
        }


class ReportItemForm(forms.ModelForm):
    class Meta:
        model = models.UserMessage
        fields = ['message']
        labels = {
            'message': 'Reason for the report',
        }

items/templates/items/category_items.html
{% extends "layout.html" %}
{% load static from staticfiles %}
{% load item_extras %}

{% block title %}{{ category.title }} | {{ block.super }}{% endblock %}

{% block content %}

    <!-- Hero Search-->
    {% hero_search %}

    <!-- Main -->
    <main class="gia-main">
        <div class="gia-archive gia-section">

            <!-- Archive Tabs -->
            <div class="row columns">
                <h2 class="text-center gia-page-heading">{{ category.title }}</h2>
                <div class="gia-archive-header">
                    <div class="gia-archive-header-wrapper">
                        <a href="{% url "items:category_items" pk=category.pk slug=category.slug %}" class="active">FREE</a>
                        <a href="{% url "items:category_items_wanted" pk=category.pk slug=category.slug %}">Wanted</a>
                    </div>
                </div>
            </div>

            <!-- List of Items -->
            {% item_archive %}

        </div>
    </main>

{% endblock %}

items/templates/items/category_items_wanted.html
{% extends "layout.html" %}
{% load static from staticfiles %}
{% load item_extras %}

{% block title %}{{ category.title }} | {{ block.super }}{% endblock %}

{% block content %}

    <!-- Hero Search-->
    {% hero_search %}

    <!-- Main -->
    <main class="gia-main">
        <div class="gia-archive gia-section">

            <!-- Archive Tabs -->
            <div class="row columns">
                <h2 class="text-center gia-page-heading">{{ category.title }}</h2>
                <div class="gia-archive-header">
                    <div class="gia-archive-header-wrapper">
                        <a href="{% url "items:category_items" pk=category.pk slug=category.slug %}">FREE</a>
                        <a href="{% url "items:category_items_wanted" pk=category.pk slug=category.slug %}" class="active">Wanted</a>
                    </div>
                </div>
            </div>

            <!-- List of Items -->
            {% item_archive %}

        </div>
    </main>

{% endblock %}

items/templates/items/choose_user.html
{% extends "layout.html" %}
{% load item_extras %}

{% block title %}Choose User | {{ block.super }}{% endblock %}

{% block content %}

    <!-- Hero Search-->
    {% hero_search %}

    <div class="gia-main gia-section">
        <div class="row column">
            <div class="gia-centered-container">
                <h4 class="text-center">Complete {{ item.name }}?</h4>
                <form method='POST' class="gia-form">
                	{% csrf_token %}
                    {{ form.as_p }}
                	<input type="submit" class="button" value="Choose User">
                    <a href="{% url 'items:home' %}">Cancel</a>
                </form>
            </div>
        </div>
    </div>

{% endblock %}

items/templates/items/item_detail.html
{% extends "layout.html" %}
{% load item_extras %}
{% load cloudinary %}


{% block title %}{{ item.name|title }} | {{ block.super }}{% endblock %}

{% block content %}

    <!-- Hero Search-->
    {% hero_search %}

    <!-- Main -->
    <main class="gia-main gia-section">
        <div class="row align-justify">

            <div class="columns small-12 medium-6 small-order-2 medium-order-1">
                <div class="gia-item-details">
                    <div class="gia-details-header">
                        <h2 class="gia-item-name">{{ item.name }}</h2>
                        <p class="gia-item-location"><span class="gia-meta-title">Located in:</span>{{ item.get_location_display }}{% if item.location_detail %}, {{ item.location_detail }}{% endif %}</p>
                        <p class="gia-item-date">
                            <span class="gia-meta-title">Posted on:</span>{{ item.posted_on|date:"t M Y" }}
                            <!-- <small>- Expires in 2 months</small> -->
                        </p>
                    </div>
                    <div class="gia-details-description">
                        <p>{{ item.details }}</p>
                    </div>
                    <div class="gia-details-footer">
                        <div class="row align-justify align-middle">
                            <div class="columns">
                                {% if item.user == request.user %}
                                    <a href="{% url 'items:update' pk=item.pk slug=item.slug %}" class="button large gia-request-button">Edit Item</a>
                                {% elif item.status == 'available' or item.status == 'awaiting' %}
                                    {% if item.post_type == 'free' %}
                                        <a href="{% url 'items:request' pk=item.pk slug=item.slug %}" class="button large gia-request-button">Request Item</a>
                                    {% else %}
                                        <a href="{% url 'items:offer' pk=item.pk slug=item.slug %}" class="button large gia-request-button">Offer Item</a>
                                    {% endif %}
                                {% endif %}
                            </div>
                            <div class="columns shrink">
                                {% include 'partials/social_share.html' %}
                            </div>
                        </div>
                        <div class="row column">
                            <p class="gia-item-availability"><span class="gia-meta-title">This item is:</span>{{ item.get_status_display }}</p>
                            {% if item.status != 'available' and item.user == request.user %}
                                <a href="{% url 'items:make_available' pk=item.pk %}">Make it Available Again</a>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>


            {% if item.image1 or item.image2 or item.image3 %}

                <!-- Images Column -->
                <div class="columns small-12 medium-6 small-order-1 medium-order-2">
                    <div class="orbit gia-single-images" role="region" aria-label="Item Images" data-orbit>
                        <ul class="orbit-container">

                            <!-- Show buttons only if there are more than one.... -->
                            {% if item.image1 and item.image2 or item.image1 and item.image3 or item.image2 and item.image3  %}
                                <button class="button-orbit orbit-previous"><span class="show-for-sr">Previous Slide</span>&#9664;&#xFE0E;</button>
                                <button class="button-orbit orbit-next"><span class="show-for-sr">Next Slide</span>&#9654;&#xFE0E;</button>
                            {% endif %}

                            {% if item.image1 %}
                                <li class="is-active orbit-slide">
                                    <img class="orbit-image" src="{% cloudinary_url item.image1 %}" alt="{{ item.name }}">
                                </li>
                            {% endif %}
                            {% if item.image2 %}
                                <li class="orbit-slide">
                                    <img class="orbit-image" src="{% cloudinary_url item.image2 %}" alt="{{ item.name }}">
                                </li>
                            {% endif %}
                            {% if item.image3 %}
                                <li class="orbit-slide">
                                    <img class="orbit-image" src="{% cloudinary_url item.image3 %}" alt="{{ item.name }}">
                                </li>
                            {% endif %}

                        </ul>
                    </div>
                </div>
            {% endif %}

            <div class="columns small-12 medium-6 small-order-3">
                <div class="gia-user-detail">
                    <div class="row columns">
                        <div class="gia-section-heading gia-underlined-heading">
                            <h4>Posted by</h4>
                        </div>
                    </div>
                    <div class="row">
                        <div class="columns">
                            <ul class="gia-user-meta">
                                <li>
                                    <span class="gia-meta-title">Member:</span>
                                    <span>{{ item.user.username }}</span>
                                </li>
                                <li>
                                    <span class="gia-meta-title">Items Given:</span>
                                    <span class="badge">{{ free_items_count }}</span>
                                </li>
                                <li>
                                    <span class="gia-meta-title">Items Taken:</span>
                                    <span class="badge">{{ wanted_items_count }}</span>
                                </li>
                            </ul>
                        </div>
                        <div class="columns">
                            <ul class="gia-user-links">
                                <li>
                                    <i class="fa fa-id-card"></i>
                                    <a href="{% url 'items:profile' username=item.user.username %}">See other items by {{ item.user.username }}</a>
                                </li>
                                <li>
                                    <i class="fa fa-question-circle"></i>
                                    <a href="{% url 'items:ask' pk=item.pk slug=item.slug %}">Ask a Question</a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>

            <div class="columns small-12 medium-6 small-order-4">
                <div class="gia-report-note">
                    <p>Something not quite right? <a href="{% url 'items:report' pk=item.pk slug=item.slug %}">Report</a></p>
                </div>
            </div>

        </div>
    </main>

{% endblock %}

items/templates/items/item_list.html
{% extends "layout.html" %}
{% load static from staticfiles %}
{% load item_extras %}

{% block title %}Home | {{ block.super }}{% endblock %}

{% block content %}

    <!-- Hero Search-->
    {% hero_search_bg %}

    <!-- Main -->
    <main class="gia-main">
        <div class="gia-archive gia-section">

            <!-- Archive Tabs -->
            <div class="row columns">
                <h5 class="gia-section-heading gia-heading-normal text-center">Give away or find FREE second hand stuff</h5>
                <div class="gia-archive-header">
                    <div class="gia-archive-header-wrapper">
                        <a href="{% url "items:home" %}" class="active">FREE</a>
                        <a href="{% url "items:home_wanted" %}">Wanted</a>
                    </div>
                </div>
            </div>

            <!-- List of Items -->
            {% item_archive %}

        </div>

        <section class="gia-section gia-steps gia-color-light">
            <div class="row columns">
                <div class="gia-section-heading text-center">
                    <h3><b>How</b> to give things away</h3>
                    <p>Be clutter free! Have someone come and take it away in 3 easy steps!</p>
                </div>
            </div>
            <div class="row align-center">
                <div class="column small-10">
                    <div class="row">
                        <div class="columns small-12 medium-4">
                            <div class="gia-iconbox">
                                <div class="gia-iconbox-icon"><i class="fa fa-camera-retro"></i></div>
                                <h4 class="gia-iconbox-title">Snap a photo and write a description</h4>
                            </div>
                        </div>
                        <div class="columns small-12 medium-4">
                            <div class="gia-iconbox">
                                <div class="gia-iconbox-icon"><i class="fa fa-users"></i></div>
                                <h4 class="gia-iconbox-title">Pick someone to give it to</h4>
                            </div>
                        </div>
                        <div class="columns small-12 medium-4">
                            <div class="gia-iconbox">
                                <div class="gia-iconbox-icon"><i class="fa fa-home"></i></div>
                                <h4 class="gia-iconbox-title">Pop it on your porch ready for collection</h4>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </main>

{% endblock %}

items/templates/items/item_wanted_list.html
{% extends "layout.html" %}
{% load static from staticfiles %}
{% load item_extras %}

{% block title %}Home - Wanted | {{ block.super }}{% endblock %}

{% block content %}

    <!-- Hero Search-->
    {% hero_search_bg %}

    <!-- Main -->
    <main class="gia-main">
        <div class="gia-archive gia-section">

            <!-- Archive Tabs -->
            <div class="row columns">
                <h5 class="gia-section-heading gia-heading-normal text-center">Give away or find FREE second hand stuff</h5>
                <div class="gia-archive-header">
                    <div class="gia-archive-header-wrapper">
                        <a href="{% url "items:home" %}">FREE</a>
                        <a href="{% url "items:home_wanted" %}" class="active">Wanted</a>
                    </div>
                </div>
            </div>

            <!-- List of Items -->
            {% item_archive %}

        </div>

        <section class="gia-section gia-steps gia-color-light">
            <div class="row columns">
                <div class="gia-section-heading text-center">
                    <h3><b>How</b> to give things away</h3>
                    <h6>Be clutter free! Have someone come and take it away in 3 easy steps!</h6>
                </div>
            </div>
            <div class="row align-center">
                <div class="column small-10">
                    <div class="row">
                        <div class="columns">
                            <div class="gia-iconbox">
                                <div class="gia-iconbox-icon"><i class="fa fa-camera-retro"></i></div>
                                <h4 class="gia-iconbox-title">Snap a photo and write a description</h4>
                            </div>
                        </div>
                        <div class="columns">
                            <div class="gia-iconbox">
                                <div class="gia-iconbox-icon"><i class="fa fa-users"></i></div>
                                <h4 class="gia-iconbox-title">Pick someone to give it to</h4>
                            </div>
                        </div>
                        <div class="columns">
                            <div class="gia-iconbox">
                                <div class="gia-iconbox-icon"><i class="fa fa-home"></i></div>
                                <h4 class="gia-iconbox-title">Pop it on your porch ready for collection</h4>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </main>

{% endblock %}

items/templates/items/make_available.html
{% extends "layout.html" %}
{% load item_extras %}

{% block title %}Make Item Available | {{ block.super }}{% endblock %}

{% block content %}

    <!-- Hero Search-->
    {% hero_search %}

    <div class="gia-main gia-section">
        <div class="row column">
            <div class="gia-centered-container">
                <h4 class="text-center">Make item: {{ item.name }} available again?</h4>
                <form method='POST' class="gia-form">
                	{% csrf_token %}
                    <input name="{{ form.status.html_name }}" id="{{ form.status.id_for_label }}"
                           value="{{ form.status.value }}" type="hidden">
                	<input type="submit" class="button" value="Make Available">
                    <a href="{% url 'items:home' %}">Cancel</a>
                </form>
            </div>
        </div>
    </div>

{% endblock %}

items/templates/items/user_profile.html
{% extends "layout.html" %}
{% load static from staticfiles %}
{% load item_extras %}

{% block title %}Profile {{ profile_user.username }} | {{ block.super }}{% endblock %}

{% block content %}

    <!-- Hero Search-->
    {% hero_search %}

    <div class="gia-section">
        <div class="row align-middle">
            <div class="column">
                <h3 class="text-center">{{ profile_user.username }}</h3>
            </div>
            <div class="column">
                <ul class="gia-profile-list">
                    <li>
                        <span class="gia-meta-title">Member Since:</span>
                        <span>{{ profile_user.date_joined|date:"t M Y"}}</span>
                    </li>
                    <li>
                        <span class="gia-meta-title">Items Given:</span>
                        <span class="badge">{{ free_items_count }}</span>
                    </li>
                    <li>
                        <span class="gia-meta-title">Items Taken:</span>
                        <span class="badge">{{ wanted_items_count }}</span>
                    </li>
                </ul>
            </div>
        </div>
    </div>

    <!-- Main -->
    <main class="gia-main">
        <div class="gia-archive gia-section">

            <!-- Archive Tabs -->
            <div class="row columns">
                <div class="gia-archive-header">
                    <div class="gia-archive-header-wrapper">
                        <a href="{% url "items:profile" username=profile_user.username %}" class="active">FREE</a>
                        <a href="{% url "items:profile_wanted" username=profile_user.username %}">Wanted</a>
                    </div>
                </div>
            </div>

            <!-- List of Items -->
            {% item_archive %}

        </div>
    </main>

{% endblock %}

items/templates/items/user_profile_wanted.html
{% extends "layout.html" %}
{% load static from staticfiles %}
{% load item_extras %}

{% block title %}Profile {{ profile_user.username }} | {{ block.super }}{% endblock %}

{% block content %}

    <!-- Hero Search-->
    {% hero_search %}

    <div class="gia-section">
        <div class="row align-middle">
            <div class="column">
                <h3 class="text-center">{{ profile_user.username }}</h3>
            </div>
            <div class="column">
                <ul class="gia-profile-list">
                    <li>
                        <span class="gia-meta-title">Member Since:</span>
                        <span>{{ profile_user.date_joined|date:"t M Y"}}</span>
                    </li>
                    <li>
                        <span class="gia-meta-title">Items Given:</span>
                        <span class="badge">{{ free_items_count }}</span>
                    </li>
                    <li>
                        <span class="gia-meta-title">Items Taken:</span>
                        <span class="badge">{{ wanted_items_count }}</span>
                    </li>
                </ul>
            </div>
        </div>
    </div>

    <!-- Main -->
    <main class="gia-main">
        <div class="gia-archive gia-section">

            <!-- Archive Tabs -->
            <div class="row columns">
                <div class="gia-archive-header">
                    <div class="gia-archive-header-wrapper">
                        <a href="{% url "items:profile" username=profile_user.username %}">FREE</a>
                        <a href="{% url "items:profile_wanted" username=profile_user.username %}" class="active">Wanted</a>
                    </div>
                </div>
            </div>

            <!-- List of Items -->
            {% item_archive %}

        </div>
    </main>

{% endblock %}