auctionsite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from . import views
from django.contrib.auth import views as django_auth_views


urlpatterns = [
    url(r'^admin/', include('admin_honeypot.urls', namespace='admin_honeypot')),
    url(r'^giaadmin/', admin.site.urls),
    url(r'^search/', include('haystack.urls')),
    url(r'^password_change/$', django_auth_views.PasswordChangeView.as_view(), name='password_change'),
    url(r'^password_change/done/$', django_auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^', include('items.urls', namespace="items")),
]

# Adding Static File Urls (for Dev environment only)
urlpatterns += staticfiles_urlpatterns()

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

items/urls.py
from django.conf.urls import include, url
from django.contrib.sitemaps.views import sitemap

from .sitemaps import ItemSitemap
from . import views

sitemaps = {
    'items': ItemSitemap()
}

urlpatterns = [

    # Sitemap
    url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),

    # Messages Actions
    url(r'^action/request-item/(?P<pk>\d+)/(?P<slug>[\w-]+)/$', views.RequestItemView.as_view(), name='request'),
    url(r'^action/offer-item/(?P<pk>\d+)/(?P<slug>[\w-]+)/$', views.OfferItemView.as_view(), name='offer'),
    url(r'^action/ask-question/(?P<pk>\d+)/(?P<slug>[\w-]+)/$', views.AskQuestionView.as_view(), name='ask'),
    url(r'^action/reply/(?P<pk>\d+)/(?P<slug>[\w-]+)/$', views.ReplyView.as_view(), name='reply'),
    url(r'^action/report-item/(?P<pk>\d+)/(?P<slug>[\w-]+)/$', views.ReportItemView.as_view(), name='report'),

    # Item CRUD Actions
    url(r'^action/create-item/$', views.ItemCreateView.as_view(), name='create'),
    url(r'^action/update-item/(?P<pk>\d+)/(?P<slug>[\w-]+)/$', views.ItemUpdateView.as_view(), name='update'),
    url(r'^action/delete-item/(?P<pk>\d+)/(?P<slug>[\w-]+)/$', views.ItemDeleteView.as_view(), name='delete'),

    # Item Completion Process
    url(r'^action/choose-user/(?P<pk>\d+)/(?P<username>[\w-]+)/$', views.ChooseUserView.as_view(), name='choose_user'),
    url(r'^action/make-available/(?P<pk>\d+)/$', views.MakeAvailableView.as_view(), name='make_available'),

    # Categories Views
    url(r'^item/category/(?P<pk>\d+)/(?P<slug>[\w-]+)/wanted-items/$', views.CategoryItemsWantedView.as_view(), name='category_items_wanted'),
    url(r'^item/category/(?P<pk>\d+)/(?P<slug>[\w-]+)/$', views.CategoryItemsView.as_view(), name='category_items'),

    # Profile View
    url(r'^user/(?P<username>\w+)/wanted/$', views.ProfileWantedView.as_view(), name='profile_wanted'),
    url(r'^user/(?P<username>\w+)/$', views.ProfileView.as_view(), name='profile'),

    # Tos
    url(r'^tos/$', views.TosTemplateView.as_view(), name='tos'),

    # Generic Views
    url(r'^dashboard/$', views.dashboard, name='dashboard'),
    url(r'^messages/$', views.profile_messages, name='profile_messages'),
    url(r'^item/(?P<pk>\d+)/(?P<slug>[\w-]+)/$', views.ItemDetailView.as_view(), name='detail'),
    url(r'^wanted-items/$', views.ItemWantedListView.as_view(), name='home_wanted'),
    url(r'^$', views.ItemListView.as_view(), name='home'),
]

items/models.py
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from django.utils import timezone
from django.template.defaultfilters import slugify
from django.db.models.signals import post_save
from django.dispatch import receiver
from cloudinary.models import CloudinaryField

from django.db import models



class Category(models.Model):
    title = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255, unique=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name_plural = "categories"
        ordering = ['title',]


class Item(models.Model):
    LOCATION_CHOICES = (
        ('AUH', 'Abu Dhabi'),
        ('AJM', 'Ajman'),
        ('SHJ', 'Sharjah'),
        ('DXB', 'Dubai'),
        ('FUJ', 'Fujairah'),
        ('RAK', 'Ras Al Khaimah'),
        ('UAQ', 'Umm Al Quwain'),
    )
    TYPE_CHOICES = (
        ('free', 'Free (I want to give something away)'),
        ('wanted', 'Wanted (I want to get something)'),
    )
    STATUS_CHOICES = (
        ('available', 'Available'),
        ('completed', 'Completed'),
        ('awaiting', 'Awaiting Pickup'),
        ('onhold', 'On Hold'),
        ('removed', 'Removed'),
    )
    name = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255)
    category = models.ForeignKey(Category, blank=True, null=True)
    other_category = models.CharField(max_length=128, blank=True, default="")
    details = models.TextField(blank=True, default="")
    posted_on = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User, related_name='item_user')
    completed_with = models.ForeignKey(User, blank=True, null=True, related_name='item_completed_with')
    location_detail = models.CharField(max_length=255, blank=True, null=True)

    # Cloudinary
    image1 = CloudinaryField('image', blank=True, null=True, default='')
    image2 = CloudinaryField('image', blank=True, null=True, default='')
    image3 = CloudinaryField('image', blank=True, null=True, default='')

    location = models.CharField(
        max_length=3,
        choices=LOCATION_CHOICES,
        default='DXB',
    )
    post_type = models.CharField(
        max_length=6,
        choices=TYPE_CHOICES,
        default='free',
    )
    status = models.CharField(
        max_length=10,
        choices=STATUS_CHOICES,
        default='available',
    )

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['-posted_on',]

    def get_absolute_url(self):
        return reverse("items:detail", kwargs={"pk":self.pk, "slug":self.slug})

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Item, self).save(*args, **kwargs)


class Activity(models.Model):
    TYPE_CHOICES = (
        ('available', 'Available'),
        ('offered', 'Offered'),
        ('requested', 'Requested'),
        ('awaiting', 'Awaiting Pickup'),
        ('completed', 'Completed'),
    )
    item = models.ForeignKey(Item, blank=True, null=True)
    user = models.ForeignKey(User, blank=True, null=True)
    date = models.DateTimeField(auto_now_add=True)
    change_type = models.CharField(
        max_length=9,
        choices=TYPE_CHOICES,
        blank=True,
        default='',
    )

    def __str__(self):
        return self.item.name

    class Meta:
        verbose_name_plural = "activities"


class UserMessage(models.Model):
    TAG_CHOICES = (
        ('request', 'Request'),
        ('offer', 'Offer'),
        ('question', 'Question'),
        ('report', 'Report'),
        ('reply', 'Reply'),
    )
    from_user = models.ForeignKey(User, related_name="usermessages")
    to_user = models.ForeignKey(User)
    item = models.ForeignKey(Item)
    date = models.DateTimeField(auto_now_add=True)
    pickup_time = models.CharField(max_length=255, blank=True, null=True)
    message = models.TextField()
    related_to = models.ForeignKey('self', blank=True, null=True)
    tag = models.CharField(
        max_length=9,
        choices=TAG_CHOICES,
        blank=True,
        default='request',
    )

    def __str__(self):
        return self.message

    class Meta:
        ordering = ['-date',]


class Profile(models.Model):
    LOCATION_CHOICES = (
        ('AUH', 'Abu Dhabi'),
        ('AJM', 'Ajman'),
        ('SHJ', 'Sharjah'),
        ('DXB', 'Dubai'),
        ('FUJ', 'Fujairah'),
        ('RAK', 'Ras Al Khaimah'),
        ('UAQ', 'Umm Al Quwain'),
    )
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    last_message_check = models.DateTimeField(blank=True, null=True)
    location = models.CharField(
        max_length=3,
        choices=LOCATION_CHOICES,
        default='DXB',
    )

    def __str__(self):
        return self.user.username


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)

@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    if not instance.is_superuser:
        instance.profile.save()

items/forms.py
from django.conf import settings
from django.contrib.auth.models import User
from django.template.defaultfilters import filesizeformat
from django.utils.translation import ugettext_lazy as _
from django import forms

from cloudinary.forms import CloudinaryFileField

from . import models



class ItemCreateForm(forms.ModelForm):
    image1 = CloudinaryFileField(
                required=False,
                options = {'crop': 'limit', 'width': 546, 'height': 1000,})
    image2 = CloudinaryFileField(
                required=False,
                options = {'crop': 'limit', 'width': 546, 'height': 1000,})
    image3 = CloudinaryFileField(
                required=False,
                options = {'crop': 'limit', 'width': 546, 'height': 1000,})
    class Meta:
        model = models.Item
        fields = ("post_type", "image1", "image2", "image3", "name", "details", "category", "other_category", "location", "location_detail")
        labels = {
            'details': _('Details (optional):'),
            'category': _('Category (optional):'),
            'other_category': _('Name the Other Category (optional):'),
            'location_detail': _('Location Detail (optional):'),
        }


class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name')


class SignupForm(forms.Form):
    accept_tos = forms.BooleanField(required=True, label='Accept terms of use')

    def signup(self, request, user):
        user.accept_tos = self.cleaned_data['accept_tos']
        user.save()


class ChooseUserForm(forms.ModelForm):
    STATUS_CHOICES = (
        ('awaiting', 'Awaiting Pickup'),
        ('completed', 'Completed'),
    )
    status = forms.ChoiceField(
        choices=STATUS_CHOICES,
    )
    class Meta:
        model = models.Item
        fields = ('status',)


class RequestForm(forms.ModelForm):
    class Meta:
        model = models.UserMessage
        fields = ['pickup_time', 'message']
        labels = {
            'pickup_time': 'Enter a date/day/time you can pickup the item:',
            'message': 'I\'d really like the item because:',
        }


class OfferForm(forms.ModelForm):
    class Meta:
        model = models.UserMessage
        fields = ['message']
        labels = {
            'message': 'Description of item offered',
        }


class ReplyForm(forms.ModelForm):
    class Meta:
        model = models.UserMessage
        fields = ['message']
        labels = {
            'message': 'Your Reply',
        }


class AskQuestionForm(forms.ModelForm):
    class Meta:
        model = models.UserMessage
        fields = ['message']
        labels = {
            'message': 'Your Question',
        }


class ReportItemForm(forms.ModelForm):
    class Meta:
        model = models.UserMessage
        fields = ['message']
        labels = {
            'message': 'Reason for the report',
        }

items/templates/items/messages/contact.html
{% extends "layout.html" %}
{% load item_extras %}

{% block title %}Request Item | {{ block.super }}{% endblock %}

{% block content %}

    <!-- Hero Search-->
    {% hero_search %}

    <!-- Main -->
    <main class="gia-main gia-section">
        <form method="POST" class="gia-form">
            <div class="row align-center">
                <div class="medium-6 columns">
                    <ul class="gia-form-meta">
                        <li>
                            <span class="gia-meta-title">To:</span>
                            <span>The moderators</span>
                        </li>
                        <li>
                            <span class="gia-meta-title">From:</span>
                            <span>{{ from_user }}</span>
                        </li>
                        <li>
                            <span class="gia-meta-title">Item:</span>
                            <span>{{ item_name }}</span>
                        </li>
                    </ul>
                    {% csrf_token %}
                    {{ form.as_p }}
                    <input type="submit" class="button" value="Send">
                </div>
            </div>
        </form>
    </main>

{% endblock %}

items/templates/items/messages/profile_messages.html
{% extends "layout.html" %}
{% load item_extras %}
{% load humanize %}

{% block title %}Messages | {{ block.super }}{% endblock %}

{% block content %}

    <!-- Hero Search-->
    {% hero_search %}

    <!-- Main -->
    <main class="gia-main gia-section">
        <div class="gia-usermessages">
            <div class="row collapse">
              <div class="small-12 large-3 columns">
                <ul class="tabs vertical" id="gia-vert-tabs" data-tabs>
                  <li class="tabs-title is-active"><a href="#panel-inbox" aria-selected="true">Inbox</a></li>
                  <li class="tabs-title"><a href="#panel-sent">Sent</a></li>
                </ul>
                </div>
                <div class="small-12 large-9 columns">
                    <div class="tabs-content vertical" data-tabs-content="gia-vert-tabs">

                        <!-- Inbox Messages -->
                        <div class="tabs-panel tabs-panel-no-padding is-active" id="panel-inbox">
                            <div class="table-row table-header">
                                <div class="table-cells small-cell">From</div>
                                <div class="table-cells large-cell">Item</div>
                                <div class="table-cells">Type</div>
                                <div class="table-cells">Date</div>
                            </div>
                            <div class="accordion" data-accordion data-allow-all-closed="true">
                                {% if inbox_messages %}
                                    {% for message in inbox_messages %}
                                        <div class="accordion-item" data-accordion-item>
                                            <a class="table-row accordion-title" href="#">
                                                {% if message.from_user.username == "admin" %}
                                                    <span class="table-cells small-cell"><i>Moderators</i></span>
                                                {% else %}
                                                    <span class="table-cells small-cell">{{ message.from_user.username }}</span>
                                                {% endif %}
                                                <span class="table-cells large-cell">{{ message.item.name }}</span>
                                                <span class="table-cells">{{ message.get_tag_display }}</span>
                                                <span class="table-cells">{{ message.date|naturaltime }}</span>
                                            </a>
                                            <div class="accordion-content" data-tab-content>
                                                <div class="accordion-content-wrapper">
                                                    <div class="gia-profile-message">

                                                        {% if message.related_to %}
                                                            <div class="gia-profile-message-panel">
                                                                <h6>Your Message: <small>({{ message.related_to.date|date:"t M Y"}})</small></h6>
                                                                <p>{{ message.related_to.message }}</p>
                                                            </div>
                                                        {% endif %}


                                                        {% if message.pickup_time %}
                                                            <div class="gia-profile-message-panel">
                                                                <h6>Pickup Time:</h6>
                                                                <p>{{ message.pickup_time }}</p>
                                                            </div>
                                                        {% endif %}
                                                        {% if message.message %}
                                                            <div class="gia-profile-message-panel">
                                                                <h6>Message:</h6>
                                                                <p>{{ message.message }}</p>
                                                            </div>
                                                        {% endif %}
                                                    </div>
                                                    <span class="gia-message-action-link">
                                                        <a href="{% url 'items:reply' pk=message.pk slug=message.item.slug %}">Reply</a>
                                                    </span>
                                                    {% if message.tag == 'request' %}
                                                        <a href="{% url 'items:choose_user' username=message.from_user.username pk=message.item.pk %}" class="gia-message-action-link">
                                                            Choose User
                                                        </a>
                                                    {% endif %}
                                                </div>
                                            </div>
                                        </div>
                                    {% endfor %}
                                {% else %}
                                    <div class="table-message">
                                        <p>Inbox empty.</p>
                                    </div>
                                {% endif %}
                            </div>
                        </div>

                        <!-- Sent Messages -->
                        <div class="tabs-panel tabs-panel-no-padding" id="panel-sent">
                            <div class="table-row table-header">
                                <div class="table-cells small-cell">To</div>
                                <div class="table-cells large-cell">Item</div>
                                <div class="table-cells">Type</div>
                                <div class="table-cells">Date</div>
                            </div>
                            <div class="accordion" data-accordion data-allow-all-closed="true">
                                {% if sent_messages %}
                                    {% for message in sent_messages %}
                                        <div class="accordion-item" data-accordion-item>
                                            <a class="table-row accordion-title" href="#">
                                                {% if message.to_user.username == "admin" %}
                                                    <span class="table-cells small-cell"><i>Moderators</i></span>
                                                {% else %}
                                                    <span class="table-cells small-cell">{{ message.to_user.username }}</span>
                                                {% endif %}
                                                <span class="table-cells large-cell">{{ message.item.name }}</span>
                                                <span class="table-cells">{{ message.get_tag_display }}</span>
                                                <span class="table-cells">{{ message.date|naturaltime }}</span>
                                            </a>
                                            <div class="accordion-content" data-tab-content>
                                                <div class="accordion-content-wrapper">
                                                    <div class="gia-profile-message">

                                                        {% if message.pickup_time %}
                                                            <div class="gia-profile-message-panel">
                                                                <h6>Pickup Time:</h6>
                                                                <p>{{ message.pickup_time }}</p>
                                                            </div>
                                                        {% endif %}
                                                        {% if message.message %}
                                                            <div class="gia-profile-message-panel">
                                                                <h6>Message:</h6>
                                                                <p>{{ message.message }}</p>
                                                            </div>
                                                        {% endif %}
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    {% endfor %}
                                {% else %}
                                    <div class="table-message">
                                        <p>No Sent messages.</p>
                                    </div>
                                {% endif %}
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </main>

{% endblock %}

items/templates/items/messages/reply.html
{% extends "layout.html" %}
{% load item_extras %}

{% block title %}Request Item | {{ block.super }}{% endblock %}

{% block content %}

    <!-- Hero Search-->
    {% hero_search %}

    <!-- Main -->
    <main class="gia-main gia-section">
        <form method="POST" class="gia-form">
            <div class="row align-center">
                <div class="medium-6 columns">
                    <ul class="gia-form-meta">
                        <li>
                            <span class="gia-meta-title">To:</span>
                            <span>{{ to_user }}</span>
                        </li>
                        <li>
                            <span class="gia-meta-title">From:</span>
                            <span>{{ from_user }}</span>
                        </li>
                        <li>
                            <span class="gia-meta-title">Item:</span>
                            <span>{{ item_name }}</span>
                        </li>
                        <li class="gia-flex-column">
                            <span class="gia-meta-title">Reply to Message:</span>
                            <span>{{ original_message }}</span>
                        </li>
                    </ul>
                    {% csrf_token %}
                    {{ form.as_p }}
                    <input type="submit" class="button" value="Send">
                </div>
            </div>
        </form>
    </main>

{% endblock %}

items/templates/items/messages/report.html
{% extends "layout.html" %}
{% load item_extras %}

{% block title %}Request Item | {{ block.super }}{% endblock %}

{% block content %}

    <!-- Hero Search-->
    {% hero_search %}

    <!-- Main -->
    <main class="gia-main gia-section">
        <form method="POST" class="gia-form">
            <div class="row align-center">
                <div class="medium-6 columns">
                    <ul class="gia-form-meta">
                        <li>
                            <span class="gia-meta-title">To:</span>
                            <span>The moderators</span>
                        </li>
                        <li>
                            <span class="gia-meta-title">From:</span>
                            <span>{{ from_user }}</span>
                        </li>
                        <li>
                            <span class="gia-meta-title">Item:</span>
                            <span>{{ item_name }}</span>
                        </li>
                    </ul>
                    {% csrf_token %}
                    {{ form.as_p }}
                    <input type="submit" class="button" value="Send">
                </div>
            </div>
        </form>
    </main>

{% endblock %}

items/templates/items/messages/request_item.html
{% extends "layout.html" %}
{% load item_extras %}

{% block title %}Request Item | {{ block.super }}{% endblock %}

{% block content %}

    <!-- Hero Search-->
    {% hero_search %}

    <!-- Main -->
    <main class="gia-main gia-section">
        <form method="POST" class="gia-form">
            <div class="row align-center">
                <div class="medium-6 columns">
                    <ul class="gia-form-meta">
                        <li>
                            <span class="gia-meta-title">To:</span>
                            <span>{{ to_user }}</span>
                        </li>
                        <li>
                            <span class="gia-meta-title">From:</span>
                            <span>{{ from_user }}</span>
                        </li>
                        <li>
                            <span class="gia-meta-title">Item:</span>
                            <span>{{ item_name }}</span>
                        </li>
                    </ul>
                    {% csrf_token %}
                    {{ form.as_p }}
                    <input type="submit" class="button" value="Send">
                </div>
            </div>
        </form>
    </main>

{% endblock %}