auctionsite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from . import views
from django.contrib.auth import views as django_auth_views


urlpatterns = [
    url(r'^admin/', include('admin_honeypot.urls', namespace='admin_honeypot')),
    url(r'^giaadmin/', admin.site.urls),
    url(r'^search/', include('haystack.urls')),
    url(r'^password_change/$', django_auth_views.PasswordChangeView.as_view(), name='password_change'),
    url(r'^password_change/done/$', django_auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^', include('items.urls', namespace="items")),
]

# Adding Static File Urls (for Dev environment only)
urlpatterns += staticfiles_urlpatterns()

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

items/urls.py
from django.conf.urls import include, url
from django.contrib.sitemaps.views import sitemap

from .sitemaps import ItemSitemap
from . import views

sitemaps = {
    'items': ItemSitemap()
}

urlpatterns = [

    # Sitemap
    url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),

    # Messages Actions
    url(r'^action/request-item/(?P<pk>\d+)/(?P<slug>[\w-]+)/$', views.RequestItemView.as_view(), name='request'),
    url(r'^action/offer-item/(?P<pk>\d+)/(?P<slug>[\w-]+)/$', views.OfferItemView.as_view(), name='offer'),
    url(r'^action/ask-question/(?P<pk>\d+)/(?P<slug>[\w-]+)/$', views.AskQuestionView.as_view(), name='ask'),
    url(r'^action/reply/(?P<pk>\d+)/(?P<slug>[\w-]+)/$', views.ReplyView.as_view(), name='reply'),
    url(r'^action/report-item/(?P<pk>\d+)/(?P<slug>[\w-]+)/$', views.ReportItemView.as_view(), name='report'),

    # Item CRUD Actions
    url(r'^action/create-item/$', views.ItemCreateView.as_view(), name='create'),
    url(r'^action/update-item/(?P<pk>\d+)/(?P<slug>[\w-]+)/$', views.ItemUpdateView.as_view(), name='update'),
    url(r'^action/delete-item/(?P<pk>\d+)/(?P<slug>[\w-]+)/$', views.ItemDeleteView.as_view(), name='delete'),

    # Item Completion Process
    url(r'^action/choose-user/(?P<pk>\d+)/(?P<username>[\w-]+)/$', views.ChooseUserView.as_view(), name='choose_user'),
    url(r'^action/make-available/(?P<pk>\d+)/$', views.MakeAvailableView.as_view(), name='make_available'),

    # Categories Views
    url(r'^item/category/(?P<pk>\d+)/(?P<slug>[\w-]+)/wanted-items/$', views.CategoryItemsWantedView.as_view(), name='category_items_wanted'),
    url(r'^item/category/(?P<pk>\d+)/(?P<slug>[\w-]+)/$', views.CategoryItemsView.as_view(), name='category_items'),

    # Profile View
    url(r'^user/(?P<username>\w+)/wanted/$', views.ProfileWantedView.as_view(), name='profile_wanted'),
    url(r'^user/(?P<username>\w+)/$', views.ProfileView.as_view(), name='profile'),

    # Tos
    url(r'^tos/$', views.TosTemplateView.as_view(), name='tos'),

    # Generic Views
    url(r'^dashboard/$', views.dashboard, name='dashboard'),
    url(r'^messages/$', views.profile_messages, name='profile_messages'),
    url(r'^item/(?P<pk>\d+)/(?P<slug>[\w-]+)/$', views.ItemDetailView.as_view(), name='detail'),
    url(r'^wanted-items/$', views.ItemWantedListView.as_view(), name='home_wanted'),
    url(r'^$', views.ItemListView.as_view(), name='home'),
]

templates/layout.html
{% load static from staticfiles %}
{% load socialaccount %}
{% load item_extras %}

<!doctype html>
<html class="no-js" lang="en">
  <head>

    <!-- MEta -->
    <meta charset="utf-8" />
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <!-- Title -->
    <title>{% block title %}Give it Away!{% endblock %}</title>

    <!-- Temp -->
    <meta name="google-site-verification" content="_Eqpo0J8sjb00crLzT3vZfsGv1GlpwNSWdqDs_KBKy8" />

    <!-- Icon -->
    <link rel="shortcut icon" type="image/png" href="{% static 'img/favicon.ico' %}" />

    <!-- Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Lato|Source+Sans+Pro" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/font-awesome.css' %}">

    <!-- Css -->
    <link rel="stylesheet" href="{% static 'css/foundation.css' %}">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">

    <!-- Static from Child Templates -->
    {% block static_head %}{% endblock %}

  </head>
  <body>

    {% include 'partials/messages.html' %}

    <!-- Top Bar -->
    <div class="gia-top-bar">
        <div class="row align-justify small-collapse medium-uncollapse">
            <div class="column">
                <!-- <i class="fa fa-question-circle"></i> -->
                <!-- <a href="#" class="gia-link-sub">Help</a> -->
            </div>
            <div class="column">
                <div class="gia-auth-buttons">
                    {% if user.is_authenticated %}
                        {% autoescape off %}
                            {% unread_messages %}
                        {% endautoescape %}
                            <i class="fa fa-envelope hide-for-small-only"></i>
                            <a href="{% url "items:profile_messages" %}">Messages</a>
                        </span>
                        <span>
                            <i class="fa fa-user hide-for-small-only"></i>
                            <a href="{% url "items:dashboard" %}">Dashboard</a>
                        </span>
                        <span>
                            <i class="fa fa-sign-out hide-for-small-only"></i>
                            <a href="{% url "account_logout" %}">Logout</a>
                        </span>
                    {% else %}
                        <span class="gia-join-link">
                            <span class="hide-for-small-only">New Here?</span>
                            <a href="{% url "account_signup" %}">Join Now</a>
                        </span>
                        <span class="gia-login-link">
                            <i class="fa fa-sign-in hide-for-small-only"></i>
                            <a href="{% url "account_login" %}">Login</a>
                        </span>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
    <!-- Header -->
    <header class="gia-main-header">
        <div class="row align-justify medium-unstack">
            <div class="column">
                <a href="{% url "items:home" %}">
                    <img class="gia-logo" src="{% static 'img/logo.png' %}" alt="">
                </a>
            </div>
            <div class="column">
                <div class="gia-cta">
                    <a href="{% url "items:create" %}" class="button gia-cta-button">List for FREE</a>
                </div>
            </div>
        </div>
    </header>

    <!-- Main Content -->
    {% block content %}{% endblock %}

    <!-- Footer -->
    <footer class="gia-main-footer gia-section">
        <div class="row column">
            <div class="gia-footer-items">
                <a href="{% url "items:home" %}">Home</a>
                {% if user.is_authenticated %}
                    <a href="{% url "items:dashboard" %}">Dashboard</a>
                    <a href="{% url "items:profile_messages" %}">Messages</a>
                {% else %}
                    <a href="{% url "account_signup" %}">Sign Up</a>
                    <a href="{% url "account_login" %}">Login</a>
                {% endif %}
                <a href="{% url "items:tos" %}">Terms of Use</a>
            </div>
        </div>
    </footer>

    <!-- Js -->
    <script src="{% static 'js/jquery.js' %}"></script>
    <script src="{% static 'js/foundation.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>

    <!-- Analytics -->
    <script>
        (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
        (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
        m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
        })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');
        ga('create', 'UA-99647609-1', 'auto');
        ga('send', 'pageview');
    </script>

    {% block javascript %}{% endblock %}

  </body>
</html>